;              
CREATE USER IF NOT EXISTS SA SALT '65946a3d2720a050' HASH 'a62816ce846ef8ba6bfb55ce4703759c6529334a60968f9f5d6cb57848e9a7e3' ADMIN;            
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 14;       
CREATE CACHED TABLE PUBLIC.ACTOR(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255)
);             
ALTER TABLE PUBLIC.ACTOR ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);   
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.ACTOR;     
CREATE CACHED TABLE PUBLIC.COMMENT(
    ID BIGINT NOT NULL,
    COMMENT VARCHAR(255),
    CREATED TIMESTAMP,
    TITLE VARCHAR(255),
    AUTHOR_ID BIGINT NOT NULL
);          
ALTER TABLE PUBLIC.COMMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT;  
CREATE CACHED TABLE PUBLIC.GENRE(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255)
);             
ALTER TABLE PUBLIC.GENRE ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);   
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.GENRE;        
CREATE CACHED TABLE PUBLIC.MOVIE(
    ID BIGINT NOT NULL,
    AVERAGE_RATING DOUBLE NOT NULL,
    CONTENT_RATING VARCHAR(255),
    CREATED DATE,
    DURATION VARCHAR(255),
    IMDB_RATING VARCHAR(255),
    ORGINAL_TITLE VARCHAR(255),
    PLOT VARCHAR(255),
    POSTER_URL VARCHAR(255),
    RELEASE_DATE DATE,
    STORY_LINE VARCHAR(255),
    TITLE VARCHAR(255),
    YEAR VARCHAR(255)
);             
ALTER TABLE PUBLIC.MOVIE ADD CONSTRAINT PUBLIC.CONSTRAINT_46 PRIMARY KEY(ID);  
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.MOVIE;    
CREATE CACHED TABLE PUBLIC.MOVIE_ACTORS(
    MOVIE_ID BIGINT NOT NULL,
    ACTORS_ID BIGINT NOT NULL
);        
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.MOVIE_ACTORS;                  
CREATE CACHED TABLE PUBLIC.MOVIE_COMMENTS(
    MOVIE_ID BIGINT NOT NULL,
    COMMENTS_ID BIGINT NOT NULL
);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MOVIE_COMMENTS;           
CREATE CACHED TABLE PUBLIC.MOVIE_GENRES(
    MOVIE_ID BIGINT NOT NULL,
    GENRES_ID BIGINT NOT NULL
);              
CREATE CACHED TABLE PUBLIC.RATING(
    ID BIGINT NOT NULL,
    RATING INTEGER NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    MOVIE_ID BIGINT
);  
ALTER TABLE PUBLIC.RATING ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);  
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.RATING;   
CREATE CACHED TABLE PUBLIC.ROLE(
    ID BIGINT NOT NULL,
    ROLE VARCHAR(255)
);              
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;     
CREATE CACHED TABLE PUBLIC.USER(
    ID BIGINT NOT NULL,
    ACTIVE BOOLEAN,
    CREATED TIMESTAMP,
    EMAIL VARCHAR(255),
    FAILED_LOGIN_ATTEMPTS INTEGER,
    LASTNAME VARCHAR(255),
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);  
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY(ID);   
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USER;               
ALTER TABLE PUBLIC.USER_ROLES ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(USER_ID, ROLES_ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_ROLES;               
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.UK_BJXN5II7V7YGWX39ET0WAWU0Q UNIQUE(ROLE);       
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UK_OB8KQYQQGMEFL0ACO34AKDTPE UNIQUE(EMAIL);      
ALTER TABLE PUBLIC.MOVIE_COMMENTS ADD CONSTRAINT PUBLIC.UK_HUPLBYXORAHF7XL5B0JIT2XB UNIQUE(COMMENTS_ID);       
ALTER TABLE PUBLIC.MOVIE_GENRES ADD CONSTRAINT PUBLIC.FKS2XL3SIRBON75MJCONGWHRBI3 FOREIGN KEY(MOVIE_ID) REFERENCES PUBLIC.MOVIE(ID) NOCHECK;   
ALTER TABLE PUBLIC.MOVIE_ACTORS ADD CONSTRAINT PUBLIC.FKOXMXJ61V0A9QS12VBOO8RXPNO FOREIGN KEY(ACTORS_ID) REFERENCES PUBLIC.ACTOR(ID) NOCHECK;  
ALTER TABLE PUBLIC.RATING ADD CONSTRAINT PUBLIC.FKLMWUH7GVB6CH5RYQ1BWGADBKN FOREIGN KEY(AUTHOR_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;         
ALTER TABLE PUBLIC.USER_ROLES ADD CONSTRAINT PUBLIC.FK55ITPPKW3I07DO3H7QOCLQD4K FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;       
ALTER TABLE PUBLIC.COMMENT ADD CONSTRAINT PUBLIC.FKH1GTV412U19WCBX22177XBKJP FOREIGN KEY(AUTHOR_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;        
ALTER TABLE PUBLIC.USER_ROLES ADD CONSTRAINT PUBLIC.FKJ9553ASS9UCTJRMH0GKQSMV0D FOREIGN KEY(ROLES_ID) REFERENCES PUBLIC.ROLE(ID) NOCHECK;      
ALTER TABLE PUBLIC.MOVIE_GENRES ADD CONSTRAINT PUBLIC.FKI8GL10TAQ0YVV0AQNUXEAL5X0 FOREIGN KEY(GENRES_ID) REFERENCES PUBLIC.GENRE(ID) NOCHECK;  
ALTER TABLE PUBLIC.MOVIE_COMMENTS ADD CONSTRAINT PUBLIC.FK96SFS80GA99A5D3LV2KRYA48G FOREIGN KEY(MOVIE_ID) REFERENCES PUBLIC.MOVIE(ID) NOCHECK; 
ALTER TABLE PUBLIC.MOVIE_ACTORS ADD CONSTRAINT PUBLIC.FKBSTO8YEF4BTOKHVEIHMKG8876 FOREIGN KEY(MOVIE_ID) REFERENCES PUBLIC.MOVIE(ID) NOCHECK;   
ALTER TABLE PUBLIC.MOVIE_COMMENTS ADD CONSTRAINT PUBLIC.FKMO0TNSV3I3QUS6VW9IUOVB44Q FOREIGN KEY(COMMENTS_ID) REFERENCES PUBLIC.COMMENT(ID) NOCHECK;            
ALTER TABLE PUBLIC.RATING ADD CONSTRAINT PUBLIC.FKLQSVMDLH3EP1BOO7IN23XE86Y FOREIGN KEY(MOVIE_ID) REFERENCES PUBLIC.MOVIE(ID) NOCHECK;         
